schema = 3

[mod]
  [mod."buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go"]
    version = "v1.36.11-20251209175733-2a1774d88802.1"
    hash = "sha256-dfB5y/lnnNa+cz3YmrTdXxDTkqk4FYu/KWQRUp5EoVE="
  [mod."buf.build/go/protovalidate"]
    version = "v1.1.0"
    hash = "sha256-B56qZWUnpch69q56EDILeuoJQGPdziJLlFbVIOfgJkI="
  [mod."buf.build/go/protoyaml"]
    version = "v0.6.0"
    hash = "sha256-rT+UDGa6MSNYJpmlelucCLOqj8ktUHidehryRVFJPYk="
  [mod."cel.dev/expr"]
    version = "v0.25.1"
    hash = "sha256-TEdMxFUPK7IZuCXMufwCkbN+ZZIXSQclljIybFZcByo="
  [mod."codeberg.org/readeck/go-readability/v2"]
    version = "v2.1.0"
    hash = "sha256-O6YmJ+nNcJnEkfy9mEge024N9EVSOB09GS7wYJ8CjBY="
  [mod."github.com/JohannesKaufmann/dom"]
    version = "v0.2.0"
    hash = "sha256-vrJG0spzGYAflEvAz0sYvD6nC6IYI5lAZbIx82GBtQE="
  [mod."github.com/JohannesKaufmann/html-to-markdown/v2"]
    version = "v2.5.0"
    hash = "sha256-xTfJNijtDlQ5oEZkl92KEyFg3U+Wl4nJcsT5puS7h4A="
  [mod."github.com/PuerkitoBio/goquery"]
    version = "v1.11.0"
    hash = "sha256-Au/xzPOirIaMb9ElkMsJtOzqXBhqM5+4K0EQIo4oaPA="
  [mod."github.com/XiaoConstantine/dspy-go"]
    version = "v0.74.0"
    hash = "sha256-CR0pNyp9lZyePXND3AwvTzfSK9z8aL3ITiMsXRBUYEA="
  [mod."github.com/XiaoConstantine/mcp-go"]
    version = "v0.3.1"
    hash = "sha256-xSTKPUDpGK/zX8233YQ/ibFgi96RIqcitdh4g1eLIjk="
  [mod."github.com/andybalholm/cascadia"]
    version = "v1.3.3"
    hash = "sha256-jv7ZshpSd7FZzKKN6hqlUgiR8C3y85zNIS/hq7g76Ho="
  [mod."github.com/anthropics/anthropic-sdk-go"]
    version = "v1.19.0"
    hash = "sha256-ubYeau5XL0tx4c/79L58rzJGOdOWs9z6WQOtN6mpgxw="
  [mod."github.com/antlr4-go/antlr/v4"]
    version = "v4.13.1"
    hash = "sha256-beAuxHNRUuhzcSJUh/8ztVf1zCUiaT72fg2Jvx0AuNQ="
  [mod."github.com/araddon/dateparse"]
    version = "v0.0.0-20210429162001-6b43995a97de"
    hash = "sha256-UuX84naeRGMsFOgIgRoBHG5sNy1CzBkWPKmd6VbLwFw="
  [mod."github.com/benbjohnson/clock"]
    version = "v1.3.5"
    hash = "sha256-pSTHNILoQpLL64bvdcNwXv+dVJ3LBZRoECpj7m8C9tw="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bep/debounce"]
    version = "v1.2.1"
    hash = "sha256-7qHOp4vB0ifEseXXBuSH6W5YNImVcb8PTWSJJAMaGcU="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/dennwc/iters"]
    version = "v1.2.2"
    hash = "sha256-ilKSLbg69mwDpAetdm1fySRiNduMB8oftiahn3Bs7KU="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/frostbyte73/core"]
    version = "v0.1.1"
    hash = "sha256-JXemW9AJ3U4xAdCJvXxXSopIrF10ML65BkzMaIqqV+M="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.9.0"
    hash = "sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g="
  [mod."github.com/gammazero/deque"]
    version = "v1.2.0"
    hash = "sha256-M4d4nK0eBPkaLgPgNPpS+YDTbEnNcj7x/Qr+zmSlmZs="
  [mod."github.com/go-chi/chi/v5"]
    version = "v5.2.3"
    hash = "sha256-fB8KidqJgWrPnnS+0uIKVOO1VRclD6nG1Lt1IeSq2M0="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.4"
    hash = "sha256-RrLHCu9l6k0XVobdZQJ9Sx/VTQcWjrdLR5BEG7yXTEQ="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-rod/rod"]
    version = "v0.116.2"
    hash = "sha256-f66euaZq7TEZOmTw7vVw0ScmKRTuYZ4Epz/fMQwZXds="
  [mod."github.com/go-shiori/dom"]
    version = "v0.0.0-20230515143342-73569d674e1c"
    hash = "sha256-4lm9KZfR2XnfZU9KTG+4jqLYZqbfL74AMO4y3dKpIbg="
  [mod."github.com/gogs/chardet"]
    version = "v0.0.0-20211120154057-b7413eaefb8f"
    hash = "sha256-4MeqBJsh4U+ZEbfdDwdciTYMlQWkCil2KJbUxHjBSIo="
  [mod."github.com/google/cel-go"]
    version = "v0.26.1"
    hash = "sha256-XVL+pNGjmLrQefpB7qj419zWl1qhPVHmVxsP/Ro1AtE="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.4-0.20250319132907-e064f32e3674"
    hash = "sha256-a8n6oe20JDpwThClgAyVhJDi6QVaS0qzT4PvRxlQ9to="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.6"
    hash = "sha256-E6THwIqVXpH2TINRVh2ygwhAlLpJ9OBqNcs5zZd4K9g="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/jxskiss/base62"]
    version = "v1.1.0"
    hash = "sha256-vpi7/XM+Xo9jUSpc6pXH8UxWxxfsWCl6ysqoLP9kBiw="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.2"
    hash = "sha256-mRa+6qEi5joqQao13ZFogmq67rOQzHCVbCCjKA+HKEc="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.3.0"
    hash = "sha256-50JhbQyT67BK38HIdJihPtjV7orYp96HknI2VP7A9Yc="
  [mod."github.com/lithammer/shortuuid/v4"]
    version = "v4.2.0"
    hash = "sha256-ZQ3dKACehQmO4xkEhWW/I7EQQKBapQjqsTDzwNXb/Zc="
  [mod."github.com/livekit/mageutil"]
    version = "v0.0.0-20250511045019-0f1ff63f7731"
    hash = "sha256-sgpsQNtsyW2buNTqPONrX/S8oQxphxpxtx9w3dN491g="
  [mod."github.com/livekit/mediatransportutil"]
    version = "v0.0.0-20251213100503-cc390ae365e9"
    hash = "sha256-6Qs5IMS07y9o5FSQqabgwktgZ3Oj5ArDhk1F2aOzgGk="
  [mod."github.com/livekit/protocol"]
    version = "v1.43.4"
    hash = "sha256-lWDzh0uKMQ6UPKRyXp+yoY7l8/uYialh78Wmbj2JwZY="
  [mod."github.com/livekit/psrpc"]
    version = "v0.7.1"
    hash = "sha256-rD2s+18r8aad8F4LDeqJ198ssON6bNELdle0ntVnFFE="
  [mod."github.com/livekit/server-sdk-go/v2"]
    version = "v2.13.1"
    hash = "sha256-BrVGd3FdwV3AkwJDFFZJ6OxzNxTtjpnub0oNShRLnG0="
  [mod."github.com/magefile/mage"]
    version = "v1.15.0"
    hash = "sha256-XH3CHsGRGQsxJkEguDJ3IrjGEeCg5bEqjcIDLpZfGpE="
  [mod."github.com/matoous/go-nanoid/v2"]
    version = "v2.1.0"
    hash = "sha256-SapI0yn7X8Ao2QOfrT1dZu67qFSLd/jqxDfk3yiYWOI="
  [mod."github.com/moby/sys/user"]
    version = "v0.4.0"
    hash = "sha256-Lk9pZFh/ERYGWkcKfVKhlDW66J13FESGD0yJcBc8+ts="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/nats-io/nats.go"]
    version = "v1.48.0"
    hash = "sha256-0Y6iOgP52jFUlAWCYPHD2R0b3ahHWTK1RDAKxLPCpTw="
  [mod."github.com/nats-io/nkeys"]
    version = "v0.4.12"
    hash = "sha256-uNvRzljA6c6ppFtZLpFmwz/c9fmDzQz44Ekys0rBZ+o="
  [mod."github.com/nats-io/nuid"]
    version = "v1.0.1"
    hash = "sha256-7wddxVz3hnFg/Pf+61+MtQJJL/l8EaC8brHoNsmD64c="
  [mod."github.com/pashagolub/pgxmock/v4"]
    version = "v4.9.0"
    hash = "sha256-VRJPDwi9Lec+R1bvni/gGlUxQc3N1mzXbiNGKAvYK40="
  [mod."github.com/pgvector/pgvector-go"]
    version = "v0.3.0"
    hash = "sha256-hXTFqDURkBvcxfzA4L4waIvQugmq5+pJ+V4ad7MRyDc="
  [mod."github.com/pion/datachannel"]
    version = "v1.5.10"
    hash = "sha256-67druailFGdnUOgCiZF4/PTSMjGk2gtKWivBLJItm3Y="
  [mod."github.com/pion/dtls/v3"]
    version = "v3.0.9"
    hash = "sha256-2fr8ZjZVzdbSbxtPzomeLzB6Kv8G/DDPnC6AEyqXgqA="
  [mod."github.com/pion/ice/v4"]
    version = "v4.1.0"
    hash = "sha256-zQzgAPqDY8QINV9V0NN0GTreVZ0xkn64EMDn0hRNDR0="
  [mod."github.com/pion/interceptor"]
    version = "v0.1.42"
    hash = "sha256-tNOGS2kC6yXIgSfDHfFBZgRrM/l/7Ive7v1k/9ADHns="
  [mod."github.com/pion/logging"]
    version = "v0.2.4"
    hash = "sha256-S3bPblOkgYbRnbuC0YVTGUh3aCdaIHEQyoK+suhwYxk="
  [mod."github.com/pion/mdns/v2"]
    version = "v2.1.0"
    hash = "sha256-eBnhv1uCXVouZF2ztfkCLqDOojrc8Hsnk84P4fJSSQk="
  [mod."github.com/pion/randutil"]
    version = "v0.1.0"
    hash = "sha256-jl6WfLPH7RV5MQhQtqwSDzhIL0D0eCnDT2L9uButveI="
  [mod."github.com/pion/rtcp"]
    version = "v1.2.16"
    hash = "sha256-Ix+zFe8E9TbuAS/oiacIcVOm8DVmauLPyYac5I9UC6U="
  [mod."github.com/pion/rtp"]
    version = "v1.8.27"
    hash = "sha256-EVforIGAowzg3HUY52owHQdf5PhcjIbP+C3KrBqcxFQ="
  [mod."github.com/pion/sctp"]
    version = "v1.9.0"
    hash = "sha256-qiuQwq6MjlJJ2WsVDWVx6UO3Cf8NnYoxlZ+/NXIvMoA="
  [mod."github.com/pion/sdp/v3"]
    version = "v3.0.17"
    hash = "sha256-srg0SflPeS0/JDDWXBY/z5zoshItRCqmnQouPWZM4tc="
  [mod."github.com/pion/srtp/v3"]
    version = "v3.0.9"
    hash = "sha256-FhGlCZRiph0wml71MOc7VRjPoKOnU4OLbih0QCXqxcg="
  [mod."github.com/pion/stun/v3"]
    version = "v3.0.2"
    hash = "sha256-ZfffkKGhfoq01yoypYNvHZisa84i++KvoPb94B1Yn1I="
  [mod."github.com/pion/transport/v3"]
    version = "v3.1.1"
    hash = "sha256-Ntwtxz7vEooBCk1unXU+dR+A+AUCt53XS5is+3DVNrk="
  [mod."github.com/pion/turn/v4"]
    version = "v4.1.3"
    hash = "sha256-l4CHgvGCKzYF54QAW6H/EF8HEkLUbXMTp+LP3Qj4bt0="
  [mod."github.com/pion/webrtc/v4"]
    version = "v4.2.1"
    hash = "sha256-CbdUTfkRjKu3lmuV7eCTjfc2AE5/w1iAyLd05HPfaQY="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.23.2"
    hash = "sha256-3GD4fBFa1tJu8MS4TNP6r2re2eViUE+kWUaieIOQXCg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.2"
    hash = "sha256-q6Fh6v8iNJN9ypD47LjWmx66YITa3FyRjZMRsuRTFeQ="
  [mod."github.com/prometheus/common"]
    version = "v0.67.4"
    hash = "sha256-CFkwP3fePnBhXZelj7JcLYc0RT192t9ZkunWEAGEC1A="
  [mod."github.com/prometheus/procfs"]
    version = "v0.19.2"
    hash = "sha256-PJW21pew9v+XA7Miow8JVPct+FPIHmQHphwO+g2kNWA="
  [mod."github.com/puzpuzpuz/xsync/v3"]
    version = "v3.5.1"
    hash = "sha256-yAf9Ye4XmtnhK3cxaUCjdGZWH+0WRNIczwCW3CPKUUw="
  [mod."github.com/redis/go-redis/v9"]
    version = "v9.17.2"
    hash = "sha256-c33dDUnqlL5JoXMOiaqo8Ry5a5nmHlv3jHteVSpOLtg="
  [mod."github.com/sourcegraph/conc"]
    version = "v0.3.0"
    hash = "sha256-mIdMs9MLAOBKf3/0quf1iI3v8uNWydy7ae5MFa+F2Ko="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.3.1"
    hash = "sha256-yptboRvbZtX+OEdlTgJnrCT+bvaMgCJp5B9ifEaSfw0="
  [mod."github.com/streamer45/silero-vad-go"]
    version = "v0.2.1"
    hash = "sha256-/9uJOTcpN7XBteA9bqQmntLIgIcbpfHprux909/2jvs="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.3"
    hash = "sha256-4s8d7MdRKq4r7QjkIFCdwjKehc6Hi5mS4xuZ2v2QYR8="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/tidwall/gjson"]
    version = "v1.18.0"
    hash = "sha256-CO6hqDu8Y58Po6A01e5iTpwiUBQ5khUZsw7czaJHw0I="
  [mod."github.com/tidwall/match"]
    version = "v1.2.0"
    hash = "sha256-O2wTU0SmNIEEOxfncl2BW2czgWeIW5vqR6+A7dtNtXI="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.1"
    hash = "sha256-S0uTDDGD8qr415Ut7QinyXljCp0TkL4zOIrlJ+9OMl8="
  [mod."github.com/tidwall/sjson"]
    version = "v1.2.5"
    hash = "sha256-OYGNolkmL7E1Qs2qrQ3IVpQp5gkcHNU/AB/z2O+Myps="
  [mod."github.com/twitchtv/twirp"]
    version = "v8.1.3+incompatible"
    hash = "sha256-j1h9YE3wl9h36DfPf92To1H/PwNk4CgerOARNO3HK1w="
  [mod."github.com/vmihailenco/msgpack/v5"]
    version = "v5.4.1"
    hash = "sha256-pDplX6xU6UpNLcFbO1pRREW5vCnSPvSU+ojAwFDv3Hk="
  [mod."github.com/vmihailenco/tagparser/v2"]
    version = "v2.0.0"
    hash = "sha256-M9QyaKhSmmYwsJk7gkjtqu9PuiqZHSmTkous8VWkWY0="
  [mod."github.com/wlynxg/anet"]
    version = "v0.0.5"
    hash = "sha256-F4JBxnY/O08YIwtjaMqEm0AV/fx42SeS7uGUhZHoQyc="
  [mod."github.com/ysmood/fetchup"]
    version = "v0.2.3"
    hash = "sha256-sJ9PBMJ/PH3Es/ngAJkrxTPNAXr7AFjdsblF67mP2Hc="
  [mod."github.com/ysmood/goob"]
    version = "v0.4.0"
    hash = "sha256-o0yVrxQRbN1dSjBH359VHADzPmkyrYOp7jn1GqIYhvw="
  [mod."github.com/ysmood/got"]
    version = "v0.40.0"
    hash = "sha256-VI/UDjV2xDjOblYxN2Dr0gxGyFMseKgCsWGx+MhZELM="
  [mod."github.com/ysmood/gson"]
    version = "v0.7.3"
    hash = "sha256-Dn5cTopPKtKCjQ7G6nlvPW2d7G4c5NfIdLVM9eLgR0E="
  [mod."github.com/ysmood/leakless"]
    version = "v0.9.0"
    hash = "sha256-nGfyb2fFT1AN33AtsCj+9xcAiK5XjHLlH/Oqc3DRyo8="
  [mod."github.com/zeebo/xxh3"]
    version = "v1.0.2"
    hash = "sha256-XXUApJ54WZeV4YBaDHNF3kLdK16nPDOZNP1Fnx1JjpI="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.2.1"
    hash = "sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.39.0"
    hash = "sha256-ExtTq4iRL2Hsh9CIPudao86Y1qtisRzIIzaH7QngEIU="
  [mod."go.opentelemetry.io/otel/exporters/stdout/stdouttrace"]
    version = "v1.39.0"
    hash = "sha256-J/ZWXpZ5JcJk0AaNqsbVfvpmLzJjmgmIBQ2AAS2GKNU="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.39.0"
    hash = "sha256-VbkFRo307Sicjk3DKOkim8ptLZafAiK3vUMQdyusxF4="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.39.0"
    hash = "sha256-GaLoc4oW2QLtJwA/FwSW3A4BqP7u0aX7f+MCfb8TFvw="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.39.0"
    hash = "sha256-5e2yJbiJPcuXq5ldOA8Z4hHIh4Ywk0MgQ9OHNqOAiRo="
  [mod."go.uber.org/atomic"]
    version = "v1.11.0"
    hash = "sha256-TyYws/cSPVqYNffFX0gbDml1bD4bBGcysrUWU7mHPIY="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.1"
    hash = "sha256-bn/MMu7X3GkUuW12Xwn9JYbOJeEu9+yoQtkmO+36xlQ="
  [mod."go.uber.org/zap/exp"]
    version = "v0.3.0"
    hash = "sha256-ZGCV0TCXUBxIqEOJL6LtQJJB36U4e6VMnZ2k0kY8r5g="
  [mod."go.yaml.in/yaml/v2"]
    version = "v2.4.3"
    hash = "sha256-WqfrOUQFvfuORgl1yyVOcsEXU/vwWQHkcVWx3vCxvaw="
  [mod."golang.org/x/crypto"]
    version = "v0.46.0"
    hash = "sha256-I8N/spcw3/h0DFA+V1WK38HctckWIB9ep93DEVCALxU="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20251219203646-944ab1f22d93"
    hash = "sha256-0n6AiDMlSiV2jc4+J2RrseVv7oypKO9q1ZUZuaC8wrM="
  [mod."golang.org/x/mod"]
    version = "v0.31.0"
    hash = "sha256-ZVNmaZADgM3+30q9rW8q4gP6ySkT7r1eb4vrHIlpCjM="
  [mod."golang.org/x/net"]
    version = "v0.48.0"
    hash = "sha256-oZpddsiJwWCH3Aipa+XXpy7G/xHY5fEagUSok7T0bXE="
  [mod."golang.org/x/sync"]
    version = "v0.19.0"
    hash = "sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno="
  [mod."golang.org/x/sys"]
    version = "v0.39.0"
    hash = "sha256-dxTBu/JAWUkPbjFIXXRFdhQWyn+YyEpIC+tWqGo0Y6U="
  [mod."golang.org/x/text"]
    version = "v0.32.0"
    hash = "sha256-9PXtWBKKY9rG4AgjSP4N+I1DhepXhy8SF/vWSIDIoWs="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20251222181119-0a764e51fe1b"
    hash = "sha256-ioNQf98NszbbMPzfCtOXLwZTWxJNZMxXcrRk4vkAwWA="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20251222181119-0a764e51fe1b"
    hash = "sha256-gdgUw1LzgVOrarF1cGBUI9uoaR/d6lur2RwxUDKnOZA="
  [mod."google.golang.org/grpc"]
    version = "v1.78.0"
    hash = "sha256-oKsu3+Eae5tpFOZ9K2ZzYh1FgdYdEnEIB1C+UIxSD+E="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.11"
    hash = "sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE="
  [mod."gopkg.in/hraban/opus.v2"]
    version = "v2.0.0-20230925203106-0188a62cb302"
    hash = "sha256-qgrYCthpRqw+1GpJoMLtUE9in/Xme0hZ6Rnlmh05K1k="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
