schema = 3

[mod]
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/vmihailenco/msgpack/v5"]
    version = "v5.4.1"
    hash = "sha256-pDplX6xU6UpNLcFbO1pRREW5vCnSPvSU+ojAwFDv3Hk="
  [mod."github.com/vmihailenco/tagparser/v2"]
    version = "v2.0.0"
    hash = "sha256-M9QyaKhSmmYwsJk7gkjtqu9PuiqZHSmTkous8VWkWY0="
