server_url: http://10.0.2.2:8080
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 127.0.0.1:9090
grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: false
noise:
  private_key_path: /tmp/headscale-test/noise_private.key
prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential
derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
database:
  type: sqlite
  sqlite:
    path: /tmp/headscale-test/db.sqlite
dns:
  magic_dns: false
  base_domain: test.local
  nameservers:
    global:
      - 8.8.8.8
log:
  level: info
